### ISSUE TITLE
[Putusan] Belum ada fitur untuk kredit ditolak

### ISSUE THREAD

**Issue by viviramadyah** [ThunderID/GO-Kredit#28]
Putusan kredit di setujui akan masuk ke realisasi
![image](https://user-images.githubusercontent.com/39518178/42120639-17224702-7c49-11e8-8e61-a332d381b359.png)

Putusan kredit di tolak belum ada fiturnya

**Comment by chelsymooy** [comment]
@viviramadyah  closed

**Comment by viviramadyah** [comment]
done
![image](https://user-images.githubusercontent.com/39518178/42202354-3f344352-7ec5-11e8-95dd-6395810b85c7.png)
