### ISSUE TITLE
[Realisasi] menggunakan login kabag_op

### ISSUE THREAD

**Issue by viviramadyah** [ThunderID/GO-Kredit#32]
Klik realisasi dengan login 2018.0006 / Kabag_Operasional
![image](https://user-images.githubusercontent.com/39518178/42195710-726c7a80-7ea4-11e8-97ee-a35a998f0018.png)

**Comment by chelsymooy** [comment]
Sudah

**Comment by viviramadyah** [comment]
done
![image](https://user-images.githubusercontent.com/39518178/42202837-15dbd216-7ec7-11e8-81a1-4bb0658839d8.png)
