### ISSUE TITLE
[Role Kasir] No Access

### ISSUE THREAD

**Issue by viviramadyah** [ThunderID/GO-Kredit#33]
Login dengan role kasir 2018.0009, menu kasir-nya belum bisa
![image](https://user-images.githubusercontent.com/39518178/42195769-d22033ea-7ea4-11e8-999b-fd0d3e2b6b8c.png)

**Comment by chelsymooy** [comment]
please recheck @viviramadyah

**Comment by viviramadyah** [comment]
done
![image](https://user-images.githubusercontent.com/39518178/42202879-40c3f49a-7ec7-11e8-891b-2e216e37ca67.png)
